/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_drafts/README': RouteRecordInfo<
      '/_drafts/README',
      '/_drafts/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/daily': RouteRecordInfo<
      '/albums/daily',
      '/albums/daily',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/miracle': RouteRecordInfo<
      '/albums/miracle',
      '/albums/miracle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/sunset': RouteRecordInfo<
      '/albums/sunset',
      '/albums/sunset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/young': RouteRecordInfo<
      '/albums/young',
      '/albums/young',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bangumi/': RouteRecordInfo<
      '/bangumi/',
      '/bangumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-07-13-pin': RouteRecordInfo<
      '/moments/2026-07-13-pin',
      '/moments/2026-07-13-pin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-07-14-nopin': RouteRecordInfo<
      '/moments/2026-07-14-nopin',
      '/moments/2026-07-14-nopin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-08-12-nine-images': RouteRecordInfo<
      '/moments/2026-08-12-nine-images',
      '/moments/2026-08-12-nine-images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-08-13-sunset': RouteRecordInfo<
      '/moments/2026-08-13-sunset',
      '/moments/2026-08-13-sunset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-08-14-nb': RouteRecordInfo<
      '/moments/2026-08-14-nb',
      '/moments/2026-08-14-nb',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/draft': RouteRecordInfo<
      '/moments/draft',
      '/moments/draft',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/hidden': RouteRecordInfo<
      '/moments/hidden',
      '/moments/hidden',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes/': RouteRecordInfo<
      '/notes/',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/测试文档': RouteRecordInfo<
      '/posts/测试文档',
      '/posts/%E6%B5%8B%E8%AF%95%E6%96%87%E6%A1%A3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/test': RouteRecordInfo<
      '/posts/test',
      '/posts/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/_drafts/README.md': {
      routes:
        | '/_drafts/README'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/daily.md': {
      routes:
        | '/albums/daily'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/miracle.md': {
      routes:
        | '/albums/miracle'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/sunset.md': {
      routes:
        | '/albums/sunset'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/young.md': {
      routes:
        | '/albums/young'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/bangumi/index.md': {
      routes:
        | '/bangumi/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/moments/2026-07-13-pin.md': {
      routes:
        | '/moments/2026-07-13-pin'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/moments/2026-07-14-nopin.md': {
      routes:
        | '/moments/2026-07-14-nopin'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/moments/2026-08-12-nine-images.md': {
      routes:
        | '/moments/2026-08-12-nine-images'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/moments/2026-08-13-sunset.md': {
      routes:
        | '/moments/2026-08-13-sunset'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/moments/2026-08-14-nb.md': {
      routes:
        | '/moments/2026-08-14-nb'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/moments/draft.md': {
      routes:
        | '/moments/draft'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/moments/hidden.md': {
      routes:
        | '/moments/hidden'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/notes/index.md': {
      routes:
        | '/notes/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/测试文档.md': {
      routes:
        | '/posts/测试文档'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/test.md': {
      routes:
        | '/posts/test'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
